### ISSUE TITLE
Add "Video generated by qMuVi" to output video

### ISSUE THREAD

**Issue by garymooney** [garymooney/qmuvi#10]
Add the text "Video generated by qMuVi" to the bottom right of the output video, as shown in the screenshot.

![image](https://user-images.githubusercontent.com/6459545/219317757-24fb13fd-ea17-4b0d-ab76-1b8f7a1af0fb.png)

**Comment by valanm22** [comment]
May I work on this?

**Comment by garymooney** [comment]
Yes, that would be great! 

I think @hvallury already has the text as a pdf. He should be able to send it to you soon.

You can create a new branch named something like issue_10_valanm22 when you're ready.

**Comment by hvallury** [comment]
[Here](https://github.com/garymooney/qmuvi/files/10904105/video_generated_by_qmuvi.zip) is a folder containing the text/logo in various formats.

**Comment by valanm22** [comment]
@garymooney how do I compile this on my pc?

**Comment by garymooney** [comment]
@valanm22 You should be able to run the demos as they are, no need to compile anything. I've just merged a new commit to the main branch that makes it even easier to run the demos. So pull the updated main branch to your local repository and follow the setup instructions in the readme. You might want to create a qmuvi python virtual environment (venv) to install the required python libraries. Once setup, just navigate to the /demos/quantum_music/ folder and run one of the demo scripts while your venv is active. For example:

`python grover_cmaj_noisy.py`

Try to make the text look as close as possible to the screenshot posted above. The resolution of the text should ideally be compatible with larger video output resolutions. In other words, if we decide to output the video at a higher resolution, the text should be at a high resolution so that it isn't pixelated.

Just another note when editing the project. We are trying to minimise the number of required package dependencies. Please try not to use packages that aren't already included after setting up the venv for qmuvi without discussing with us first. 

Please feel free to ask if you have any questions and let me know how you go.

-- Gary

**Comment by garymooney** [comment]
> @garymooney how do I compile this on my pc?

@valanm22 I've just added you as a collaborator so that you can contribute.
