### ISSUE TITLE
ionq qiskit

### ISSUE THREAD

**Issue by minminjao** [garymooney/qmuvi#32]
* qmuvi version: latest
* Python version: latest
* Operating System: pycharm

### Description

Hello, I was wondering if I could use the hardware and coding of ionq instead of qiskit for Qmuvi. For example, I want to know if there is no error when I enter the code of 'from qiskit_ionq import IonQProvider' and use the grammar written in ionq.

**Comment by garymooney** [comment]
Hi @minminjao 

As far as I'm aware, there should be no errors. However, qmuvi currently only works using simulators, so you won't be able to run it on IonQ physical devices. It should be possible though, by making qmuvi perform full quantum state tomography to get the density matrices at each of the samples. A simpler partial implementation could be to just use the measured probabilities, although this hasn't been fully implemented either. Some initial logic for this idea has already been added for the video display. But not for the simulation or midi creation.

It would be pretty cool and useful to run on physical devices wouldn't it. I'll open a new issue (#33) for implementing it :). I'll work on it when I can but I'm pretty busy atm, and we are currently prioritising issues #31, #1 and #3.

**Comment by minminjao** [comment]
okay thank you!
